server:
  port: 8083

spring:
  application:
    name: book-service
  
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/book_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: book_user
    password: book_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        instance-id: ${spring.application.name}:${server.port}
        hostname: localhost
        ip-address: 127.0.0.1
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 30s
        health-check-timeout: 10s

security:
  jwt:
    secret: "mySuperSecretKeyForJWTGenerationThatIsAtLeast32CharactersLong"
  aes:
    secret-key: "MDEyMzQ1Njc4OWFiY2RlZmdoaWprbG1ub3BxcnN0dXY="

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.university: DEBUG
